baseURL = "/"
languageCode = "en-us"
title = "MVR IT Limited"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "MVR IT Limited"
    meta_og_title = "MVR IT Limited"
    meta_og_type = "website"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "MVR IT Limited"
    meta_twitter_card = "summary"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
